messages:
  noPerm: "&cYou cannot execute this command. You need the following permission node: %node%"
  help: "&bAvailable commands:\n&e/pumpkinShooter give (username) &b- Give the specified player (or yourself) a Pumpkin Shooter"
  givenMessage: "&ePumpkin Shooter has been given to &c%playerName%&e!"
  notOnline: "&c%givenName% &eis not online!"
  wait: "&eYou are still on delay. Wait &c%waitTime% more seconds &eplease!"
  throw: "&eYou have thrown a pumpkin!"
  mustBePlayer: "&cYou cannot give yourself a Pumpkin Shooter, you are the console!"
settings:
  item-id: NETHERITE_SWORD
  useDelayInSeconds: 10
  vectorMultiplier: 2
  secondsBeforePumpkinExplosion: 4
  displayName: "&c&lPumpkin Shooter"
  lore:
    - "&eThis is a pumpkin shooter"
    - "&eBe careful, it is a dangerous tool!"
  holograms: true
  tracers: true
  tracersTicks: 2
  particleCount: 2
  particleOffsetX: 0.3
  particleOffsetY: 0.3
  particleOffsetZ: 0.3
  particleSize: 3
  particleR: 245
  particleG: 159
  particleB: 19
  timerIntervalTicks: 10
  blocksTimerAboveItem: 1.5
  hologramLines:
    - "&6&lPumpkin"
    - "&eIt will explode in &b&l%seconds% &eseconds!"