name: PumpkinShooter
version: '1.1'
main: me.zwoosks.pumpkinshooter.PumpkinShooter
api-version: 1.18
author: zwoosks
softdepend: [DecentHolograms]
commands:
  pumpkinShooter:
    description: Main PumpkinShooter plugin command.
    usage: /<command>
    permission: pumpkinshooter.maincommand
    aliases: [pshooter, pms]
